### ISSUE TITLE
mvp

### ISSUE THREAD

**Issue by quanvo87** [quanvo87/Proxy#74]
need:
- [x] add icons and pods attribution to readme
- [x] refactor names of storyboard elements
- [ ] notifications
- [x] make login splash videos not mute music playing on device
- [x] user input length limits
- [x] delete proxy
- [x] set up separate test DB
- [x] change unread message display for cells
- [x] read messages
- [x] paginate load for messages
- [x] paginate load for convos
- [x] remove convo count
- [x] show proxy count in proxies vc title
- [x] deal with race condition #126 
- [x] pop vc on viewdidappear when the object it's displaying has been deleted
- [x] make dependency container
- [x] improve protocol logic?
- [x] change me tab to settings
- [ ] sound
- [x] filler text for empty table views
- [x] loading indicators?

future:
- [ ] other messages features #122 
- [ ] profanity filter?
- [ ] google/phone number/guest login?
